'use client';

import { Card, CardContent } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { GeneratedImage } from '@/types';
import { Download, ExternalLink } from 'lucide-react';
import Image from 'next/image';

interface ImageCardProps {
  image: GeneratedImage;
  modelName: string;
  prompt: string;
  isLoading?: boolean;
}

export const ImageCard = ({ image, modelName, prompt, isLoading = false }: ImageCardProps) => {
  const handleDownload = () => {
    // Open image in new tab instead of downloading due to CORS
    window.open(image.image, '_blank');
  };

  const handleOpenInNewTab = () => {
    window.open(image.image, '_blank');
  };

  if (isLoading) {
    return (
      <Card className="w-full">
        <CardContent className="p-6">
          <div className="flex justify-between items-center mb-4">
            <Badge variant="secondary">{modelName}</Badge>
          </div>
          <div className="aspect-square bg-muted rounded-lg flex items-center justify-center">
            <div className="text-center space-y-2">
              <div className="w-8 h-8 border-2 border-primary border-t-transparent rounded-full animate-spin mx-auto"></div>
              <p className="text-sm text-muted-foreground">Generating...</p>
            </div>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className="w-full">
      <CardContent className="p-6">
        <div className="flex justify-between items-center mb-4">
          <Badge variant="secondary">{modelName}</Badge>
          <div className="flex gap-2">
            <Button size="sm" variant="outline" onClick={handleDownload}>
              <ExternalLink className="w-4 h-4" />
            </Button>
          </div>
          </div>
        </div>
        <div className="aspect-square relative rounded-lg overflow-hidden bg-muted">
          <Image
            src={image.image}
            alt={`Generated by ${modelName}: ${prompt}`}
            fill
            className="object-cover"
            unoptimized
          />
        </div>
      </CardContent>
    </Card>
  );
};
